<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR79fUVb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR79fUVb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR79fUVb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR79fUVb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR79fUVb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'R79fUVb',
    'container.build_id' => 'bd629173',
    'container.build_time' => 1660647117,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR79fUVb');
